== Getting Started

=== Repository

Use this repository for SNAPSHOT builds. Releases are on Maven Central
[source,groovy]
----
repositories {
    maven {
        url 'https://oss.sonatype.org/content/groups/public'
    }
}
----
=== Dependencies
==== JVM Projects

[source,groovy]
----
dependencies {
    implementation 'io.jumpco.open:kfsm-jvm:0.9.1'
}
----

==== KotlinJS Projects

[source,groovy]
----
dependencies {
    implementation 'io.jumpco.open:kfsm-js:0.9.1'
}
----

==== Kotlin/Native Projects using WASM

[source,groovy]
----
dependencies {
    implementation 'io.jumpco.open:kfsm-wasm32:0.9.1'
}
----

==== Kotlin/Native Projects using LinuxX64

[source,groovy]
----
dependencies {
    implementation 'io.jumpco.open:kfsm-linuxX64:0.9.1'
}
----

==== Kotlin/Native Projects using MinGW64

[source,groovy]
----
dependencies {
    implementation 'io.jumpco.open:kfsm-mingwX64:0.9.1'
}
----

==== Kotlin/Native Projects using macOS

[source,groovy]
----
dependencies {
    implementation 'io.jumpco.open:kfsm-macosX64:0.9.1'
}
----

== DSL
The DSL provides a way of configuring the statemachine.
The statemachine supports:

* Transitions: internal and external
* Guard expressions
* Entry and exit actions per state and globally
* Default actions per state and globally
* Named statemaps
* Push and pop transitions
* Automatic transitions

All configuration calls are eventually applied to link:javadoc/kfsm/io.jumpco.open.kfsm/-state-machine-builder/index.html[StateMachineBuilder]

=== `stateMachine {}`
The top level element is `stateMachine` either by using the function

* link:javadoc/kfsm/io.jumpco.open.kfsm/-state-machine-builder/state-machine.html[StateMachineBuilder::stateMachine]
* link:javadoc/kfsm/io.jumpco.open.kfsm/state-machine.html[stateMachine]

[source,kotlin]
----
// using builder function
val definition = StateMachineBuilder<StateEnum,EventEnum,ContextType>(StateEnum.values().toSet()).stateMachine {
    default { // global defaults
    }
    initial { // initial state expression
    }
    initialMap { // define expression for deriving state stack for nested maps.
    }
    stateMap { // define named state map
    }
    state { // state definition
    }
}.build()
// using global function
val definition = stateMachine(StateEnum.values().toSet(), EventEnum::class,ContextType::class) {
    default { // global defaults
    }
    initial { // initial state expression
    }
    initialMap { // define expression for deriving state stack for nested maps.
    }
    stateMap { // define named state map
    }
    state { // state definition
    }
}.build()
----

=== `default {}`
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-handler/default.html[DslStateMachineHandler::default]
* Mandatory: _Optional_
* Cardinality: _Multiple_

Provide default configuration for entry and exit actions as well as a default action.

Example:
[source,kotlin]
----
default {
    action { // global action
    }
    entry { // global state entry action
    }
    exit { // global state exit action
    }
    transition { // default transitions
    }
}
----

==== action {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-default-event-handler/action.html[DslStateMachineDefaultEventHandler::action]
* Mandatory: _Optional_
* Cardinality: _Single_

Provide a lambda `C.(S,E, Array<out Any>)->Unit` that will be invoked when no other transitions are matched.

Example:
[source,kotlin]
----
action { currentState, event, args -> // global default action
    contextFunction()
    anotherContextFunction()
}
----

==== entry {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-default-event-handler/entry.html[DslStateMachineDefaultEventHandler::entry]
* Mandatory: _Optional_
* Cardinality: _Single_

Provide a lambda `C.(S,S,Array<out Any>) -> Unit` that will be invoked before a change in the state of the FSM.
Global entry actions will be called for all external transitions after state specific entry actions.

Example:
[source,kotlin]
----
entry { fromState, targetState, args ->
    println("Entering:$targetState from $fromState with ${args.toList()}")
}
----

==== exit {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-default-event-handler/exit.html[DslStateMachineDefaultEventHandler::exit]
* Mandatory: _Optional_
* Cardinality: _Single_

Provide a lambda `C.(S,S,Array<out Any>) -> Unit` that will be invoked after a change in the state of the FSM.
Global exit actions will be called for all external transitions after state specific entry actions.

Example:
[source,kotlin]
----
exit { fromState, targetState, args ->
    println("Exiting:$fromState to $targetState with ${args.toList()}")
}
----
==== transition(E [to S]) {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-default-event-handler/transition.html[DslStateMachineDefaultEventHandler::transition]
* Mandatory: _Optional_
* Cardinality: _Multiple_

This defines a transition when a specific event is receive and no other transition was matched.
There are 2 variations, the first is internal and doesn't define a target state, the second is external and defines a target state.
In both cases the lambda type is `C.(Array<out Any) -> Unit`

Example:
[source,kotlin]
----
transition(Event.EVENT) { args -> // default internal state action for given event
    someFunction()
}

transition(Event.EVENT to State.STATE) { args-> // default external state action for given event
    anotherFunction()
}
----

=== `initial {}`
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-handler/initial.html[DslStateMachineHandler::initial]
* Mandatory: _Optional_
* Cardinality: _Single_

Provide a lambda `C.() -> S` that will determine the state of the state machine.

Example:
[source,kotlin]
----
initial {
    when(flag) {
        1 -> State.S1
        2 -> State.S2
        else -> error("Invalid state")
    }
}
----

=== `state(currentState: S) {}`
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-handler/state.html[DslStateMachineHandler::state]
* Mandatory: _Mandatory_
* Cardinality: _Multiple_

Each `state` block decribes the transitions for a given state.

Example:
[source,kotlin]
----
state(State.STATE) {
    default { // default action for State.STATE
    }
    entry { // entry action for State.STATE
    }
    exit { // exit action for State.STATE
    }
    transition(Event.EV2 to State.S1, guard = {flag == 1 }) { // external transition with guard expression
    }
    transition(Event.EV2 to State.S1) { // external transition
    }
    transition(Event.EV1, guard = { flag == 2 }) { // internal transition with guard expression
    }
    transition(Event.EV1) { // internal guard expression
    }
    pushTransition(Event.EV2, "mapName", State.S1, gaurd = { flag == 1}) { // push transition to new map with guard expression
    }
    pushTransition(Event.EV2, "mapName", State.S1) { // push transition to new map
    }
    popTransition(Event.EV3) { // pop transition without targetState
    }
    popTransition(Event.EV3, State.S2) { // pop transition changing state while executing current action only
    }
    popTransition(Event.EV3, "newMap", State.S3) { // pop transition leading into new push transition while executing current action only
    }
    automatic(State.S1, guard = { flag == 1}) { // automatic transition to new state when guard is met
    }
    automatic(State.S1) { // automatic transition to new state
    }
}
----

==== default {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-event-handler/default.html[DslStateMachineEventHandler::default]
* Mandatory: _Optional_
* Cardinality: _Single_

A state block may have one default action which is a lambda of type `C.(S,E,Array<out Any>) -> Unit` that is invoked when no other transition is found for the given state and event and guard expressions.

Example:
[source,kotlin]
----
default { fromState, event, args -> // default state action
    someDefaultAction()
}
----

==== entry {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-event-handler/entry.html[DslStateMachineEventHandler::entry]
* Mandatory: _Optional_
* Cardinality: _Single_

This defines a lambda of type `C.(S,S,Array<out Any>) -> Unit` that will be invoked after the transition action for an external transition.

Example:
[source,kotlin]
----

entry { fromState, targetState, args -> // state entry action
    println("Entering:$targetState from $fromState with ${args.toList()}")
}
----
==== exit {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-event-handler/exit.html[DslStateMachineEventHandler::exit]
* Mandatory: _Optional_
* Cardinality: _Single_

This defines a lambda of type `C.(S,S,Array<out Any>) -> Unit` that will be invoked before the transition action for an external transitions.

Example:
[source,kotlin]
----
exit { fromState, targetState, args -> // state exit action
    println("Exiting:$fromState to $targetState with ${args.toList()}")
}
----
==== automatic(targetState: S [, guard:{}]) {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-map-event-handler/automatic.html[DslStateMachineDefaultEventHandler::automatic]
* Mandatory: _Optional_
* Cardinality: _Multiple_

There are 2 variations of automatic transitions: Those with and without guards.
An automatic transition is exercises after the state machine has completed processing a transition.
All automatic transitions attached to a given state will be invoked if their guards are met.

==== automaticPop(targetState: S [, guard:{}]) {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-map-event-handler/automatic-pop.html[DslStateMachineDefaultEventHandler::automaticPop]
* Mandatory: _Optional_
* Cardinality: _Multiple_

There are 6 variations of automatic transitions: Those with and without guards, those with and without targetMaps which will lead to a new push transition.

==== automaticPush(targetMap: String, targetState: S [, guard:{}]) {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-map-event-handler/automatic-push.html[DslStateMachineDefaultEventHandler::automaticPush]
* Mandatory: _Optional_
* Cardinality: _Multiple_

There are 2 variations of automatic transitions: Those with and without guards


==== popTransition(event: E [to targetState: S]|[,targetMap: String, targetState: S], [guard:{}]) {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-event-handler/pop-transition.html[DslStateMachineEventHandler::popTransition]
* Mandatory: _Optional_
* Cardinality: _Multiple_

There are 6 variations of popTransitions to provide for with and without guards, with and without a new state and with and without a targetMap that will result in a new push transition.

==== pushTransition(event: E, targetMap: String, targetState: S [, guard:{}]) {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-map-event-handler/push-transition.html[DslStateMachineEventHandler::pushTransition]
* Mandatory: _Optional_
* Cardinality: _Multiple_

There are 2 variations of automatic transitions: Those with and without guards

==== transition(event: E [to targetState: S],[guard: {}]) {}
* Handler: link:javadoc/kfsm/io.jumpco.open.kfsm/-dsl-state-machine-event-handler/transition.html[DslStateMachineEventHandler::transition]
* Mandatory: _Optional_
* Cardinality: _Multiple_

There are 4 variations of transitions: External and internal, with and without a guard expression.

This defines a transition action for a given event.
For an external transition a target state must be provided, while an internal transition must have no targetState.
An optional guard expression can be provided. The order in which the DSL encounters guard expression determine the evaluation order.
The first matching guard expression will determine the transition that will be used.
Their may be only one transition without a guard expression.

Examples:
[source,kotlin]
----
transition(Event.EV1, guard = { flag == 1 }) { args -> // internal transition with guard expression
}
transition(Event.EV1 to State.S2, guard = { flag == 2}) { args -> // external transition with guard expression
}
transition(Event.EV1) { args -> // internal transition
}
transition(Event.EV2 to State.S2) { args -> // external transition
}
----
