@startuml

[*] --> STATE1
STATE1 ---> STATE2 : EVENT1\n{ action1() }
STATE2 ---> STATE1 : EVENT2\n{ action2() }
STATE1 ---> STATE1 : EVENT2\n{ action3() }
STATE2 ---> STATE2 : EVENT1\n{ action4() }

@enduml
