@startuml

actor Consumer
boundary StateMachineInstance
control Context

Consumer ----> StateMachineInstance : sendEvent(event:E)

    activate StateMachineInstance
    note right of StateMachineInstance
        StateMachineInstance determines the TransitionRules
        or default exit / entry / action(s) needed
    end note
    activate StateMachineInstance
    StateMachineInstance ----> StateMachineInstance : exit {}
    StateMachineInstance ----> Context : action {}
    activate Context
    note right of Context
        Context performs the action(s)
    end note
    Context ---->  StateMachineInstance
    deactivate Context
    StateMachineInstance ----> StateMachineInstance : entry {}
    StateMachineInstance ----> StateMachineInstance : executeAutomatic
    deactivate StateMachineInstance
    return

@enduml
