@startuml

skinparam classFontSize 9
skinparam classFontName Monospaced

[*] --> LOCKED
LOCKED --> UNLOCKED : UNLOCK
UNLOCKED ---> LOCKED : LOCK
DOUBLE_LOCKED ---> LOCKED : UNLOCK
LOCKED --> DOUBLE_LOCKED : LOCK

@enduml
