@startuml

skinparam monochrome true

class C {
}
enum S {
}
enum E {
}

class StateMachineBuilder<S, E, C> {
    initial(action: C.(Any[]) -> S)
    initialMap(action: C.(Any[]) -> List<StateMapItem<S>>)
    transition(startState: S, event: E, targetState: S[, guard: C.()->Boolean], action: C.(Any[]) -> Unit)
    automatic(startState: S, targetState: S[, guard: C.()->Boolean], action: C.(Any[]) -> Unit)
    automaticPop(startState: S[,  targetState: S][, targetMap: String][, guard: C.()->Boolean], action: C.(Any[]) -> Unit)
    automaticPush(startState: S,  targetState: S, targetMap: String[, guard: C.()->Boolean], action: C.(Any[]) -> Unit)
    pushTransition(startState: S, event: E, targetMap: String, targetState: S[, guard: C.()->Boolean], action: C.(Any[]) -> Unit)
    popTransition(startState: S, event: E[, targetMap: String][, targetState: S][, guard: C.()->Boolean], action: C.(Any[]) -> Unit)
    entry(currentState: S, action: C.(Any[]) -> Unit)
    exit(currentState: S, action: C.(Any[]) -> Unit)
    defaultTransition(startState: S, event: E[, targetState: S], action: C.(Any[]) -> Unit)
    defaultAction(action: C.( S, E, Any[]) -> Unit)
    defaultEntry(action: C.( S, S, Any[]) -> Unit)
    defaultExit(action: C.( S, S, Any[]) -> Unit)
    default(currentState: S, action: C.( S, E, Any[]) -> Unit)
    stateMachine()
}

class StateMachineDefinition<S, E, C> {
    allowed(currentState: S, includeDefaults: Boolean): Set<E>
    eventAllowed(event: E, currentState: S, includeDefault: Boolean): Boolean
    create(context: C, initialState: S?) : StateMachineInstance<S,E,C>
}

class StateMachineInstance<S, E, C> {
    StateMachineInstance(context: Context, fsm: StateMachine<States,Events,Context>, initialState: S?)
    currentState: S
    sendEvent(event: E, Any[])
    allowed(includeDefaults: Boolean): Set<E>
    eventAllowed(event: E, includeDefault: Boolean): Boolean
}

StateMachineBuilder .left.> S : <<states>>
StateMachineBuilder .right.> E : <<events>>
StateMachineBuilder .up.> C : <<context>>

StateMachineDefinition .left.> S : <<states>>
StateMachineDefinition .right.> E : <<events>>
StateMachineDefinition .up.> C : <<context>>

StateMachineInstance *---> StateMachineDefinition : definition
StateMachineInstance *-left-> C : context

@enduml
