@startuml

skinparam monochrome true
skinparam StateFontName Helvetica
skinparam defaultFontName Monospaced
skinparam defaultFontStyle Bold
skinparam state {
    FontColor Black
    FontStyle Bold
}

[*] --> LOCKED
LOCKED ---> UNLOCKED : COIN\n{ unlock() }
UNLOCKED ---> LOCKED : PASS\n{ lock() }
LOCKED ---> LOCKED : PASS\n{ alarm() }
UNLOCKED ---> UNLOCKED : COIN\n{ returnCoin() }

@enduml
