@startuml

skinparam classFontSize 9
skinparam classFontName Monospaced

[*] --> LOCKED
LOCKED ---> UNLOCKED : COIN\n{ unlock() }
UNLOCKED ---> LOCKED : PASS\n{ lock() }
LOCKED ---> LOCKED : PASS\n{ alarm() }
UNLOCKED ---> UNLOCKED : COIN\n{ returnCoin() }

@enduml
