@startuml

skinparam monochrome true

actor Consumer
boundary TurnStileFSM
control Turnstile

Consumer -------> TurnStileFSM : coin()
TurnStileFSM ------> Turnstile : unlock()
Consumer -------> TurnStileFSM : coin()
TurnStileFSM ------> Turnstile : returnCoin()
Consumer -------> TurnStileFSM : pass()
TurnStileFSM ------> Turnstile : lock()
Consumer -------> TurnStileFSM : pass()
TurnStileFSM ------> Turnstile : alarm()

@enduml
