== Visualization
State Definitions can be generated as link:https://plantuml.com/[PlantUML] state diagrams or link:https://asciidoctor.org/[Asciidoc] formatted state tables.

=== Simple Visualization

The simple visualization uses the resulting definition and can render states and transitions.
You will typically add a method to a unit test class as follows:

[source,kotlin]
----
@Test
fun produceVisualizationTurnstileFSM() {
    println("== TurnStile")
    val visualization = visualize(TurnstileFSM.definition) // <1>
    File("generated", "turnstile.plantuml").writeText(plantUml(visualization)) // <2>
}
----
<1> `TurnstileFSM.definition` is the definition that will be rendered.
<2> The `plantuml` method accepts the output of `visualize` and produces a state diagram in the plantuml format.

=== Detail Visualisation

You may invoke the parser from a unit test similar to the simple case.

[source,kotlin]
----
@Test
fun produceVisualizationTurnstileFSM() {
    println("== TurnStile")
    val visualization = parseStateMachine("TurnstileFSM", File("src/test/kotlin/Turnstile.kt")) // <1>
    println(visualization)
    File("generated-parsed", "turnstile.plantuml").writeText(plantUml(visualization)) // <2>
    File("generated-parsed", "turnstile.adoc").writeText(asciiDoc(visualization)) // <3>
}
----
<1> Provide classname for the class holding the definition DSL and the sourcefile where the class may be found.
<2> Use the `plantuml` method to generate the text for a plantuml state diagram.
<3> Use the `asciidoc` method to generate an Asciidoc formatted state table.

==== Detail Visualization with Gradle Plugin

===== Configuration

====== Gradle Groovy DSL
[source,groovy]
----
kfsmViz {
    fsm('PacketReaderFSM') {
        input = file('src/main/kotlin/PacketReader.kt') // <1>
        isGeneratePlantUml = true // <2>
        isGenerateAsciidoc = true // <3>
        output = 'packet-reader' // <4>
        outputFolder = file('generated') // <5>
        plantUmlName = 'packet-reader-statediagram.plantuml' // <6>
        asciidocName = 'packet-reader-state-table.adoc'      // <7>
    }
}
----
<1> `input: File`: Required, fully qualified filename of relevant source file
<2> `isGeneratePlantUml: Boolean`: Required default is false
<3> `isGenerateAsciidoc: Boolean`: Required default is false
<4> `output: String`: Optional filename base. The default is the classname
<5> `outputFolder: File`: Optional directory for output file. Default is `$buildDir/generated`
<6> `plantUmlName: String`: Optional filename for plantuml output. Default is `$output.plantuml`
<7> `asciidocName: String`: Optional name of Asciidoc output file. Default is `$output.adoc`

====== Example with multiple state machines.
[source,groovy]
----
kfsmViz {
    fsm('TurnstileFSM') {
        input = file('resources/Turnstile.kt')
        output = 'turnstile'
        outputFolder = file('generated')
        isGeneratePlantUml = true
        isGenerateAsciidoc = true
    }
    fsm('PacketReaderFSM') {
        input = file('resources/PacketReader.kt')
        output = 'packet-reader'
        outputFolder = file('generated')
        isGeneratePlantUml = true
        isGenerateAsciidoc = true
    }
}

----
